name: CI Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: python -m compileall -q .

      # - name: Run training smoke test
      #   run: pytest tests/test_train_smoke.py -q || true

      # - name: Run API schema tests
      #   run: pytest tests/test_api_schema.py -q || true

      - name: Train
        run: python src/train.py

      - name: Evaluate
        run: python src/evaluate.py

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cal-housing-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/cal-housing-api:latest
      
      - name: Restart Container
        run: |
          docker stop cal-housing-api || true
          docker rm cal-housing-api || true
          docker run -d --name cal-housing-api -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/cal-housing-api:latest
